### ISSUE TITLE
(-215:Assertion failed) !ssize.empty() in function 'cv::resize'

### ISSUE THREAD

**Issue by majed330** [imdeepmind/processed-imdb-wiki-dataset#1]
error in trying running the wiki_image.py file.  In the step of processing all the images and merge them with the meta, the code goes running for the first 5 Batches and throw an error. 
here is the trace for the error
-------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-9-ae20031295fe> in <module>()
     37         img = cv2.imread(path, 1)
     38 
---> 39         img = cv2.resize(img, (150,150))
     40 
     41         img = img.flatten()

error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

**Comment by imdeepmind** [comment]
I have updated the project. Please have a look at the project now.
