### ISSUE TITLE
Can you share "meta.csv" file?

### ISSUE THREAD

**Issue by sebastiaopamplona** [imdeepmind/processed-imdb-wiki-dataset#2]
Hello! At this moment, the imdb.mat file, available from the official IMDB-WIKI website, is corrupted. You said that you converted both (imdb.mat and wiki.mat) into a single meta.csv. Would you be so kind as to share this meta.csv with me? It would help me a lot with my MSc thesis... Thanks in advance.

**Comment by elpapi42** [comment]
Im interested too

**Comment by sebastiaopamplona** [comment]
> Im interested too

If you download the dataset from the IMDB-WIKI website, the IMDB filenames contain the date of birth and the date the photo was taken (eg. <some_text>_<date of birth>_<date taken>.jpg). So if all you need is the age, you can extract it from the filenames.
