### ISSUE TITLE
Which dataset?

### ISSUE THREAD

**Issue by HuseynG** [imdeepmind/processed-imdb-wiki-dataset#4]
In the link you provided, there are more than one dataset, which one would be suitable to your project? Btw, it seems you did a great job, hopefully your project will be helpful. 
(Notee: I want to donwload the cropped and labeled data, 7GB big, for face recognition but I am not still not sure.)
Thanks

**Comment by imdeepmind** [comment]
I've worked on this a long time back, so don't remember clearly what I used, most likely I used the cropped face one.

Here is the link: https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/static/imdb_crop.tar

**Comment by HuseynG** [comment]
I tryied multiple ones it is 7GB and 1GB document.
